name: recipe_recommendation_app
description: A new Flutter project.
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  riverpod: ^2.3.6
  http: ^1.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
flutter:
  uses-material-design: true
  assets:
    - assets/images/